### ISSUE TITLE
vat_moss.id.validate() doesn't support strings

### ISSUE THREAD

**Issue by kdeldycke** [wbond/vat_moss-python#2]
A `unicode` instance is working but not an `str` instance:

```python
>>> vat_moss.__version__
'0.11.0'

>>> vat_moss.id.validate(u'FR12000045202')
(u'FR', u'FR12000045202', 'SAM ROBERTSHAW')

>>> vat_moss.id.validate('FR12000045202')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "python2.7/site-packages/vat_moss/id.py", line 89, in validate
    vat_id = normalize(vat_id)
  File "python2.7/site-packages/vat_moss/id.py", line 43, in normalize
    raise ValueError('VAT ID is not a string')
ValueError: VAT ID is not a string
```

I think you should replace line 13 of https://github.com/wbond/vat_moss-python/blob/d020105432813bbb91f22c539b60190fa692933b/vat_moss/id.py#L13 from:
```python
    str_cls = str
```
to:
```python
    str_cls = basestring
```

**Comment by wbond** [comment]
This design decision is on purpose. I need the input to be unicode so I can ensure the encoding that is being sent to the webservice is correct and not some random string of bytes.

Just an FYI, `basestring` was removed in Python 3.
